### PR TITLE
Move main.go to top-level.

### PR DESCRIPTION
**Pull request by jorinvo**
Makes fakedata *go-gettable*.

Or am I missing any reason here for having a `cmd/` directory?
Doesn't seem like there will be other binaries in this repo.

### CODE REVIEW

**Comment by lucapette** [comment]
This breaks the `make build` command I think. I'm not sure what's the advantage of making it go gettable but maybe I'm missing something, can you please explain why that would help? I'm following the suggestions from [this post](https://peter.bourgon.org/go-best-practices-2016/#repository-structure) which claims that the current structure makes the package go gettable so I'm even a bit confused now :)

**Comment by jorinvo** [comment]
Thanks for pointing out. I fixed the Makefile.

Many users like to install Go tools via `go get`. It works on any platform with Go install. 

With the current setup this doesn't work:
```
$ go get github.com/lucapette/fakedata/
package github.com/lucapette/fakedata: no buildable Go source files in /Users/jorin/go/src/github.com/lucapette/fakedata
```

What still works is `go get github.com/lucapette/fakedata/...`.

I also like the architecture Peter suggests in this article. 
However, I think that having a `cmd/` directory is only useful for projects that have more than one binary.
Since fakedata is single cli tool, there is no advantage in keeping `cmd/`.

**Comment by lucapette** [comment]
I have to admin I like more the structure with cmd even if there's a single binary in place but I don't like the fact the command then has to be `go get github.com/lucapette/fakedata/...` so I'm going to merge this despite my personal opinion :)

Thank you for taking care of it!

**Comment by jorinvo** [comment]
Thanks you 👍

**Pull request merged**
